info:
  app:
    name: "auth"
    description: "Auth service"
    version: "1.0.0"
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  datasource:
    hikari:
      max-lifetime: 1800000  # 30 phút
      idle-timeout: 300000   # 5 phút
    url: jdbc:postgresql://47.130.37.245:5432/effimate_dev?currentSchema=auth
    driverClassName: org.postgresql.Driver
    username: effimate
    password: hpz_jbq@dqw_ZHP5ejv